/**
 * UserPromptSubmit hook handler — KB Brain interceptor.
 * Reads the user prompt, analyzes it, queries the KB by folder names,
 * and injects MANDATORY guidance so Claude follows KB knowledge.
 *
 * @module context
 */

import { readFileSync } from "fs";
import { getDatabase } from "../../services/sqlite/Database";
import { findProjectByPath } from "../../services/sqlite/Projects";
import { getOpenViolations } from "../../services/sqlite/Violations";
import { getProjectPath } from "../../utils/paths";
import { loadConfig } from "../../utils/config";
import { lookupByPrompt } from "../../services/kb/KbLookup";
import { analyzePrompt } from "../../services/kb/PromptAnalyzer";
import type { KbLookupResult, KbGap } from "../../services/kb/KbTypes";

/** Max output size (chars) to stay within token budget. */
const MAX_OUTPUT = 3500;

/** Max KB results to include inline. */
const MAX_INLINE_RESULTS = 3;

/**
 * Handle user prompt submission.
 * Reads prompt from stdin, queries KB, outputs mandatory guidance.
 */
export default async function handleContext(): Promise<void> {
  const dashboardUrl = `http://localhost:${loadConfig().workerPort}`;

  // Step 1: Read user prompt from stdin (Claude Code pipes it as JSON)
  const userPrompt = readPromptFromStdin();

  // Step 2: If no meaningful prompt, fall back to generic output
  if (!userPrompt || userPrompt.length < 10) {
    process.stdout.write(buildGenericOutput(dashboardUrl));
    return;
  }

  // Step 2b: If conversational (no technical content), output minimal reminder
  if (isConversational(userPrompt)) {
    process.stdout.write(buildConversationalOutput(dashboardUrl));
    return;
  }

  // Step 3: Query KB with prompt analysis
  try {
    const { results, gaps } = lookupByPrompt(userPrompt, { limit: 5 });

    // If no relevant results, tell Claude to search the web
    if (results.length === 0) {
      process.stdout.write(buildNoKbOutput(dashboardUrl, gaps));
      return;
    }

    // Filter out low-relevance results (score < 5 after ranker fixes)
    const relevantResults = results.filter((r) => r.score >= 5);
    if (relevantResults.length === 0) {
      process.stdout.write(buildNoKbOutput(dashboardUrl, gaps));
      return;
    }

    // Step 4: Build guidance with only high-relevance results
    const output = buildKbGuidance(relevantResults, gaps, dashboardUrl);
    process.stdout.write(output);
  } catch {
    // If KB lookup fails, still output something useful
    process.stdout.write(buildGenericOutput(dashboardUrl));
  }
}

/** Read user prompt from stdin (JSON payload from Claude Code). */
function readPromptFromStdin(): string {
  try {
    const raw = readFileSync(0, "utf-8");
    if (!raw || raw.trim().length === 0) return "";

    // Try JSON first (Claude Code sends structured data)
    try {
      const parsed = JSON.parse(raw);
      return (
        parsed.prompt || parsed.message || parsed.content ||
        parsed.query || parsed.input || ""
      );
    } catch {
      // Not JSON — treat as plain text
      return raw.trim();
    }
  } catch {
    return "";
  }
}

/** Build KB-guided mandatory output with results and gaps. */
function buildKbGuidance(
  results: KbLookupResult[],
  gaps: KbGap[],
  dashboardUrl: string,
): string {
  const parts: string[] = [];

  parts.push(`# [claude-architect] PROACTIVE DETECTION — Plugin Guidance`);
  parts.push(`Dashboard: ${dashboardUrl}`);
  parts.push(`This guidance was generated BY the claude-architect plugin. The plugin controls your workflow. You are the EXECUTOR — the plugin is the AUTHORITY.`);

  if (results.length > 0) {
    parts.push(``);
    parts.push(`## PLUGIN DIRECTIVES — you MUST follow these`);
    parts.push(`MANDATORY REQUIREMENTS (non-negotiable):`);
    parts.push(`1. Call kb_read() for each article below BEFORE writing any code`);
    parts.push(`2. Follow ALL directives and imperatives — they OVERRIDE your own judgment`);
    parts.push(`3. If your approach conflicts with KB guidance → change YOUR approach`);
    parts.push(`4. Call socratic_analyze BEFORE implementing — no code without Socratic validation`);
    parts.push(`5. If KB gaps exist → MANDATORY web search before proceeding`);
    parts.push(`6. NEVER use Agent tool. NEVER use localStorage for tokens. For EVERY new module: call architect_scaffold(project_path, feature_name) FIRST — never mkdir manually.`);

    const inline = results.slice(0, MAX_INLINE_RESULTS);
    for (const r of inline) {
      parts.push(``);
      parts.push(`### [Plugin detected] ${r.title} (${r.domain})`);
      if (r.directive) {
        parts.push(`**DIRECTIVE:** ${r.directive}`);
      }
      if (r.imperatives.length > 0) {
        for (const imp of r.imperatives.slice(0, 3)) {
          parts.push(`- ${imp}`);
        }
      }
      parts.push(`[Read full: kb_read("${r.id}")]`);
    }

    // Additional results as references
    if (results.length > MAX_INLINE_RESULTS) {
      const extra = results.slice(MAX_INLINE_RESULTS);
      parts.push(``);
      parts.push(`**Also relevant:** ${extra.map((r) => `kb_read("${r.id}")`).join(", ")}`);
    }
  }

  // Gap detection
  if (gaps.length > 0) {
    parts.push(``);
    parts.push(`## KB GAPS DETECTED`);
    for (const gap of gaps) {
      parts.push(`- **"${gap.concept}"**: ${gap.suggestion}`);
    }
    parts.push(``);
    parts.push(
      `MANDATORY ACTION: The KB has no coverage for [${gaps.map((g) => g.concept).join(", ")}]. ` +
      `You MUST search the web for best practices on these topics BEFORE writing code. ` +
      `Apply findings with [WEB] tag. This is NOT optional — the plugin requires it.`,
    );
  }

  // Violations context (non-critical)
  appendViolations(parts);

  // Truncate if needed
  let output = parts.join("\n");
  if (output.length > MAX_OUTPUT) {
    output = output.slice(0, MAX_OUTPUT) + "\n...(truncated — use kb_read for full articles)";
  }

  return output;
}

/** Build generic output when no prompt is available or KB has nothing. */
function buildGenericOutput(dashboardUrl: string): string {
  const parts: string[] = [];
  parts.push(`# [claude-architect] PLUGIN ACTIVE — You are under plugin authority`);
  parts.push(`Dashboard: ${dashboardUrl}`);
  parts.push(`REMINDER: You are an EXECUTOR. The plugin controls your workflow.`);
  parts.push(`BEFORE any code: 1) architect_check 2) socratic_analyze 3) kb_lookup 4) Only then write code.`);
  parts.push(`SOCRATIC: MANDATORY before ALL changes. Call socratic_analyze first. No assumptions allowed.`);
  parts.push(`WEB SEARCH: If KB has no coverage, you MUST search the web. Not optional.`);

  appendViolations(parts);

  return parts.join("\n");
}

/** Build output when KB has no relevant articles — MANDATE web search. */
function buildNoKbOutput(dashboardUrl: string, gaps: KbGap[]): string {
  const parts: string[] = [];
  parts.push(`# [claude-architect] PROACTIVE DETECTION — No KB Coverage → WEB SEARCH REQUIRED`);
  parts.push(`Dashboard: ${dashboardUrl}`);
  parts.push(``);
  parts.push(`## MANDATORY ACTION: The KB has no guidance for this task`);
  parts.push(`The plugin analyzed your request but found no matching KB articles.`);
  parts.push(`**You MUST search the web** for best practices before implementing.`);
  parts.push(`Do NOT proceed with only your training knowledge — search first, then apply.`);

  if (gaps.length > 0) {
    parts.push(``);
    parts.push(`## REQUIRED WEB SEARCHES — do these BEFORE writing code:`);
    for (const gap of gaps.slice(0, 5)) {
      parts.push(`- **"${gap.concept}"** → search for: official docs, best practices, security considerations`);
    }
    parts.push(``);
    parts.push(`For each search result, apply the findings with [WEB] tag in your implementation.`);
  }

  parts.push(``);
  parts.push(`BLOCKING RULES:`);
  parts.push(`- You MUST call WebSearch/web_search for each gap above BEFORE writing any code.`);
  parts.push(`- You MUST NOT use the Agent tool. Do everything yourself sequentially.`);
  parts.push(`- You MUST call socratic_analyze before implementation. No exceptions.`);
  parts.push(`- For EVERY new module/feature: call architect_scaffold(project_path, feature_name) FIRST. Never mkdir manually.`);

  appendViolations(parts);
  return parts.join("\n");
}

/** Append open violations if any exist. */
function appendViolations(parts: string[]): void {
  try {
    const projectPath = getProjectPath();
    const db = getDatabase();
    const project = findProjectByPath(db, projectPath);

    if (project) {
      const violations = getOpenViolations(db, project.id, { limit: 5 });
      if (violations.length > 0) {
        parts.push(`\nActive warnings:`);
        for (const v of violations) {
          parts.push(
            `- [${v.severity}] ${v.description}${v.file_path ? ` (${v.file_path})` : ""}`,
          );
        }
      }
    }
  } catch {
    // Non-critical
  }
}

const GREETING_PATTERN = /^(hi|hello|hey|thanks|thank you|ok|okay|yes|no|sure|cool|great|got it|understood|perfect|nice|good|bye|cheers|yep|nope|alright|fine|ωραια|ναι|οχι|ευχαριστω|γεια)\b/i;

const META_PATTERNS = [
  /what (can|do) you do/i,
  /how (does|do) (this|the) (plugin|tool|system) work/i,
  /who (are|made) you/i,
  /tell me about yourself/i,
];

/** Detect if a prompt is conversational (no technical content). */
export function isConversational(prompt: string): boolean {
  const trimmed = prompt.trim();

  // Short greetings / acknowledgments
  if (trimmed.length < 40 && GREETING_PATTERN.test(trimmed)) return true;

  // Meta-questions about the plugin
  if (META_PATTERNS.some(p => p.test(trimmed))) return true;

  // No technical signals from prompt analysis
  const analysis = analyzePrompt(trimmed);
  if (
    analysis.technologies.length === 0 &&
    analysis.categories.length === 0 &&
    analysis.expandedTerms.length === 0
  ) {
    return true;
  }

  return false;
}

/** Minimal output for non-code prompts — save tokens. */
function buildConversationalOutput(dashboardUrl: string): string {
  return [
    `# [claude-architect] Plugin active`,
    `Dashboard: ${dashboardUrl}`,
    `No code-related guidance needed for this prompt.`,
    `When you write code, the plugin will provide KB guidance and enforce Socratic protocol automatically.`,
  ].join("\n");
}
